# Generated by Django 5.2.5 on 2025-08-23 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=50)),
            ],
            options={
                'verbose_name': 'contacts',
                'verbose_name_plural': 'contacts',
            },
        ),
    ]
